[package]
name = "ella"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
huffman-compress = "0.6.1"
bit-vec = "0.6.3"
arcode = "0.2.3"
byteorder="1.4.3"